import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, relative, extname, basename } from 'path';

interface DocPage {
  title: string;
  description: string;
  url: string;
  content: string;
}

const docsDir = 'content/docs';

function parseFrontmatter(content: string): { frontmatter: Record<string, string>; body: string } {
  const match = content.match(/^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/);
  if (!match) {
    return { frontmatter: {}, body: content };
  }

  const raw = match[1];
  const body = match[2];
  const frontmatter: Record<string, string> = {};

  for (const line of raw.split('\n')) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    // Remove surrounding quotes
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    frontmatter[key] = value;
  }

  return { frontmatter, body };
}

function getAllMdxFiles(dir: string): string[] {
  const files: string[] = [];
  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...getAllMdxFiles(fullPath));
    } else if (extname(entry.name) === '.mdx') {
      files.push(fullPath);
    }
  }

  return files;
}

function slugify(filePath: string): string {
  // Convert file path to URL slug
  const rel = relative(docsDir, filePath);
  const withoutExt = rel.replace(/\.mdx$/, '');
  // Remove locale suffix (.es) for default English pages
  const withoutLocale = withoutExt.replace(/\.es$/, '');
  // index files map to the directory
  const parts = withoutLocale.split('/');
  if (parts[parts.length - 1] === 'index') {
    parts.pop();
  }
  return '/docs/' + parts.join('/');
}

function main() {
  const files = getAllMdxFiles(docsDir);
  const pages: DocPage[] = [];

  for (const file of files) {
    const raw = readFileSync(file, 'utf-8');
    const { frontmatter, body } = parseFrontmatter(raw);

    // Skip Spanish translations — the AI assistant works in English
    if (basename(file, '.mdx').endsWith('.es')) continue;

    const title = frontmatter.title ?? 'Untitled';
    const description = frontmatter.description ?? '';
    const url = slugify(file);

    // Strip JSX components for plain text search content
    const content = body
      .replace(/<[^>]+>/g, '')
      .replace(/\{[^}]+\}/g, '')
      .replace(/```[\s\S]*?```/g, (match) => match.replace(/\n/g, ' '))
      .replace(/`([^`]+)`/g, '$1')
      .trim();

    pages.push({ title, description, url, content });
  }

  const output = `// Auto-generated by scripts/build-docs-data.ts
// Do not edit manually

export interface DocPage {
  title: string;
  description: string;
  url: string;
  content: string;
}

export const docsPages: DocPage[] = ${JSON.stringify(pages, null, 2)};
`;

  writeFileSync('functions/api/_docs-data.ts', output);
  console.log(`Generated docs data for ${pages.length} pages`);
}

main();
